<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>CycloSketchAddin</RootNamespace>
    <AssemblyName>CycloSketchAddin</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SolidWorks.Interop.sldworks" Version="32.1.0" />
    <PackageReference Include="SolidWorks.Interop.swconst" Version="32.1.0" />
    <PackageReference Include="SolidWorks.Interop.swpublished" Version="32.1.0" />
  </ItemGroup>

</Project>
